### ISSUE TITLE
Building CUDA openEMS?

### ISSUE THREAD

**Issue by 0xCoto** [aWZHY0yQH81uOYvH/Newtons-Fractal-CUDA#1]
Hi, sorry for asking this question in the wrong repository, but I couldn't find a different way to contact you (issues are disabled in forks).

I'd like to ask whether there's been any updates on the GPU acceleration of openEMS. Are there any instructions on compiling it? I'm trying to adjust the CUDA code so it runs faster.

Cheers,
Apostolos

**Comment by aWZHY0yQH81uOYvH** [comment]
Sorry for not getting to this earlier. I used the usual CMake process with `-DWITH_CUDA=YES` if I remember correctly. I've answered with more detail on the forum.
